### PR TITLE
Document data upload

### PR DESCRIPTION
**Pull request by KochTobi**

### CODE REVIEW

**Review by Steffengreiner — CHANGES_REQUESTED** [review]
Nice description easy to understand well done! 

I'd approve the PR once  "the connect to the ftp server" section also provides the information necessary to connect to the server. (e.g. that the zdv account and pw have to provided, Server name, VPN connection established before connection.) 

Additionally, as discussed some screenshots would improve the understanding as well 👍  (Although not required in the first step).

**Comment by KochTobi** [comment]
@Steffengreiner I would need some help with the merging of the mkdocs.yml file

**Comment by KochTobi** [comment]
> I'd approve the PR once "the connect to the ftp server" section also provides the information necessary to connect to the server. (e.g. that the zdv account and pw have to provided, Server name, VPN connection established before connection.)

The `prerequesites` section describes these points. I highlighted them in the text.

**Review by Steffengreiner — APPROVED** [review]
Perfect 👌

**Pull request merged**
